version: '3.8'

services:
  web:
    image: php:8.1-apache  # Use a versão do PHP que preferir
    container_name: gestao_campeonatos_web
    ports:
      - "8080:80"  # Mapeia a porta 8080 do host para a porta 80 do container
    volumes:
      - ./gestao_campeonatos:/var/www/html  # Mapeia o diretório do projeto para o container
    depends_on:
      - db

  db:
    image: mysql:5.7  # Use a versão do MySQL que preferir
    container_name: gestao_campeonatos_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # Defina uma senha para o usuário root
      MYSQL_DATABASE: gestao_campeonatos  # Nome do banco de dados
      MYSQL_USER: root  # Nome de usuário
      MYSQL_PASSWORD: user_password  # Senha do usuário
    ports:
      - "3306:3306"  # Porta padrão do MySQL
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: