version: '3.8'

services:
  web:
    build:
      context: ./php
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - phpmyadmin
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql_host
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network: